project_id = "robotization-platform"
[api]
enabled = true
port = 25421
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000
[db]
port = 25422
shadow_port = 25420
major_version = 17
[studio]
enabled = false
port = 25423
[local_smtp]
enabled = false
port = 25424
[realtime]
enabled = false
[storage]
enabled = false
[analytics]
enabled = false
[edge_runtime]
enabled = false
[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["http://127.0.0.1:5173"]
jwt_expiry = 3600
enable_signup = true
[auth.email]
enable_signup = true
[auth.external.google]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET)"
