import {useEffect,useRef,useState} from 'react';
import type {SupabaseClient,Session} from '@supabase/supabase-js';
import {getAuth} from './auth';
import {api,download} from './utils';
import ImportPanel from './ImportPanel';
type Organization={id:string;name:string};
type SavedScenario={id:string;name:string;payload:unknown;version:number};
export default function Account({payload,onLoad,onClose}:{payload:unknown;onLoad:(x:unknown,ownerId:string)=>void;onClose:()=>void}){
 const priorUser=useRef('');const [userId,setUserId]=useState('');
 const [client,setClient]=useState<SupabaseClient|null>(null),[token,setToken]=useState(''),[email,setEmail]=useState(''),[message,setMessage]=useState('Проверяем подключение…'),[orgs,setOrgs]=useState<Organization[]>([]),[org,setOrg]=useState(''),[name,setName]=useState(''),[items,setItems]=useState<SavedScenario[]>([]),[invite,setInvite]=useState(''),[role,setRole]=useState('viewer'),[history,setHistory]=useState<SavedScenario[]>([]),[editing,setEditing]=useState<SavedScenario|null>(null),[google,setGoogle]=useState(false);
 useEffect(()=>{let active=true;let dispose:(()=>void)|undefined;getAuth().then(({client:c,configuration:auth})=>{if(!active)return;if(!c){setMessage('Облачный кабинет ещё не подключён. Можно работать без входа и сохранять сценарии в этом браузере.');return;}setClient(c);setGoogle(auth.googleConfigured);const apply=(session:Session|null)=>{if(!active)return;const id=session?.user.id??'';if(priorUser.current!==id){setOrgs([]);setOrg('');setItems([]);setHistory([]);setEditing(null);setName('');setInvite('');}priorUser.current=id;setUserId(id);setToken(session?.access_token??'');setEmail(session?.user.email??'');setMessage(auth.googleConfigured?'':'База подключена, но вход Google ещё не настроен.');};c.auth.getSession().then(({data})=>apply(data.session));const {data}=c.auth.onAuthStateChange((_event,session)=>apply(session));dispose=()=>data.subscription.unsubscribe();}).catch(()=>setMessage('Сервис кабинетов недоступен. Локальные сценарии можно экспортировать.'));return()=>{active=false;dispose?.();};},[]);
 useEffect(()=>{if(token)api('/organizations','GET',undefined,token).then(d=>setOrgs(d.organizations??d)).catch(e=>setMessage(String(e.message)));},[token]);
 const refresh=async(id:string)=>{setOrg(id);setHistory([]);setEditing(null);if(id){try{const d=await api('/organizations/'+id+'/scenarios','GET',undefined,token);setItems(d.scenarios??d);}catch(e){setMessage(String(e));}}};
 const perform=async(fn:()=>Promise<void>)=>{setMessage('');try{await fn();}catch(e){setMessage(e instanceof Error?e.message:'Операция не выполнена');}};
 return <div className="overlay" onClick={onClose}><section className="modal account" role="dialog" aria-modal="true" aria-label="Кабинет организации" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose} aria-label="Закрыть">×</button><span className="eyebrow">Приватное пространство</span><h2>Кабинет организации</h2><p>Объекты, сценарии и история доступны только участникам вашей организации.</p>{message&&<p role="status" className="notice">{message}</p>}
 {!token&&client&&google&&<button className="primary" onClick={()=>perform(async()=>{const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin}});if(error)throw error;})}>Войти через Google</button>}
 {token&&<><div className="row"><span>{email}</span><button onClick={()=>client?.auth.signOut()}>Выйти</button></div><label>Организация<select value={org} onChange={e=>refresh(e.target.value)}><option value="">Выберите организацию</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Название<input value={name} onChange={e=>setName(e.target.value)} maxLength={200}/></label><div className="row"><button onClick={()=>perform(async()=>{const d=await api('/organizations','POST',{name},token);const item=d.organization??d;setOrgs([...orgs,item]);await refresh(item.id);})}>Создать организацию</button><button disabled={!org||!name} className="primary" onClick={()=>perform(async()=>{await api('/organizations/'+org+'/scenarios','POST',{name,payload},token);await refresh(org);setMessage('Сценарий сохранён.');})}>Сохранить текущий сценарий</button></div>
 {items.map(s=><div className="saved-row" key={s.id}><div><strong>{s.name}</strong><small>Версия {s.version}</small></div><button onClick={()=>{onLoad(s.payload,userId);onClose();}}>Открыть</button><button onClick={()=>perform(async()=>{await api('/organizations/'+org+'/scenarios/'+s.id,'PUT',{name:s.name,payload,expectedVersion:s.version},token);await refresh(org);setMessage('Текущая оценка записана новой версией.');})}>Записать текущую оценку</button><button onClick={()=>perform(async()=>{const d=await api('/organizations/'+org+'/scenarios/'+s.id+'/history','GET',undefined,token);setHistory(d.history);setEditing(s);})}>История</button><button onClick={()=>perform(async()=>{const d=await api('/organizations/'+org+'/scenarios/'+s.id+'/export','GET',undefined,token);download('scenario.json',JSON.stringify(d.scenario.payload,null,2));})}>Экспорт</button></div>)}
 {editing&&<button className="primary" onClick={()=>perform(async()=>{await api('/organizations/'+org+'/scenarios/'+editing.id,'PUT',{name:name||editing.name,payload,expectedVersion:editing.version},token);await refresh(org);setMessage('Новая версия сохранена атомарно.');})}>Сохранить новую версию «{editing.name}»</button>}{history.map((h,i)=><div className="saved-row" key={i}><strong>Версия {h.version} · {h.name}</strong><button onClick={()=>onLoad(h.payload,userId)}>Загрузить в рабочую область</button></div>)}{org&&<ImportPanel org={org} token={token}/>}{org&&<><h3>Доступ коллег</h3><label>Email<input type="email" value={invite} onChange={e=>setInvite(e.target.value)}/></label><label>Роль<select value={role} onChange={e=>setRole(e.target.value)}><option value="viewer">Просмотр</option><option value="editor">Редактирование</option></select></label><button onClick={()=>perform(async()=>{const d=await api('/organizations/'+org+'/invitations','POST',{email:invite,role},token);setMessage('Приглашение создано. Передайте коллеге токен: '+(d.token??d.invitation?.token??'см. ответ сервиса'));})}>Создать приглашение</button><p className="muted">Отправка писем не выполняется автоматически.</p></>}
 <h3>Принять приглашение</h3><label>Токен<input value={invite} onChange={e=>setInvite(e.target.value)}/></label><button onClick={()=>perform(async()=>{await api('/invitations/accept','POST',{token:invite},token);const d=await api('/organizations','GET',undefined,token);setOrgs(d.organizations??d);setMessage('Доступ получен.');})}>Присоединиться</button></>}
 </section></div>;
}
