import {useState} from 'react';
import {economicFields,evaluateEconomics,evaluateModel,modelFields,type CalculationResult,type FieldDefinition,type Measurement,type ModelKind,type Benefit} from '../../packages/domain';
import {download,number} from './utils';

export type CalculationDraft={currency:string;vat:'included'|'excluded';mode:'purchase'|'lease'|'subscription';horizon:string;source:string;inputs:Record<string,string>;modelInputs:Record<string,string>;benefits:Benefit[];confirmed:boolean;constant:boolean};
export const emptyDraft:CalculationDraft={currency:'RUB',vat:'excluded',mode:'purchase',horizon:'',source:'',inputs:{},modelInputs:{},benefits:[],confirmed:false,constant:false};
const titles:Record<string,string>={CAPEX:'Первоначальные затраты',annualOPEX:'Годовой OPEX',grossBenefit:'Годовая денежная выгода',netEffect:'Чистый годовой эффект',payback:'Окупаемость, лет',roi:'ROI за горизонт, %',tco:'TCO за горизонт',npv:'NPV',releasedHours:'Высвобождено часов в год',requiredUnits:'Требуется единиц',capacityPerHour:'Мощность, операций/ч',capacityOverWindow:'Мощность за период',utilizationRequired:'Требуемая загрузка, доля',shortfallPerHour:'Дефицит, операций/ч',coverageCapacity:'Площадь за период, м²',requiredHours:'Требуется часов',inspectedCount:'Проверено единиц',precision:'Точность обнаружений, доля',recall:'Полнота, доля',specificity:'Специфичность, доля',accuracy:'Доля верных решений',falsePositiveRate:'Ложная отбраковка, доля',falseNegativeRate:'Пропуск дефектов, доля'};
export function Results({result,label}:{result:CalculationResult|null;label:string}){return <section className="panel results"><span className="eyebrow">{label}</span>{!result?<div className="empty compact"><h3>Здесь появится расчёт</h3><p>Нужны значения и источник измерений. Неизвестные суммы оставьте пустыми.</p></div>:<><p className={'status '+result.status}>{result.status==='complete'?'Расчёт выполнен':result.status==='incomplete'?'Недостаточно исходных данных':'Проверьте исходные данные'}</p>{result.errors.length>0&&<ul className="errors">{result.errors.map((e,i)=><li key={i}>{e}</li>)}</ul>}{result.missing.length>0&&<details open><summary>Не заполнено: {result.missing.length}</summary><ul>{result.missing.map(e=><li key={e}>{[...economicFields,...Object.values(modelFields).flat()].find(f=>f.key===e.replace('inputs.',''))?.label??e}</li>)}</ul></details>}{result.status==='complete'&&<div className="metrics">{Object.entries(result.metrics).map(([k,v])=><div className="metric" key={k}><span>{titles[k]??k}</span><strong>{number(v)}</strong></div>)}</div>}<small>Модель {result.version}. Результат зависит от введённых данных.</small>{result.trace.length>0&&<details><summary>Формулы и происхождение</summary>{result.trace.map((t,i)=><div className="trace" key={i}><strong>{t.key}</strong><code>{t.formula}</code><small>{t.inputs.join(' · ')}</small></div>)}</details>}<button className="text-button" onClick={()=>download('calculation.json',JSON.stringify(result,null,2))}>Скачать результат и trace ↓</button></>}</section>;}
function Fields({fields,values,onChange,currency}:{fields:FieldDefinition[];values:Record<string,string>;onChange:(key:string,value:string)=>void;currency?:string}){return <div className="form-grid">{fields.map(f=><label key={f.key}>{f.label}<div className="input-unit"><input type="number" min={f.min} max={f.max} step={f.integer?'1':'any'} value={values[f.key]??''} onChange={e=>onChange(f.key,e.target.value)}/><span>{currency?f.unit.replace('currency',currency):f.unit}</span></div><small>{f.description}</small></label>)}</div>;}
function measurements(fields:FieldDefinition[],values:Record<string,string>,source:string,currency?:string){const output:Record<string,Measurement>={};for(const field of fields){const v=values[field.key];if(v!==undefined&&v.trim()!=='')output[field.key]={value:Number(v),unit:currency?field.unit.replace('currency',currency):field.unit,sourceRef:source};}return output;}
const benefitKinds={cash_saving:'Сокращение расходов',avoided_hire:'Предотвращённый найм',margin:'Дополнительная маржа',loss_reduction:'Снижение потерь',time_released:'Высвобождённое время',nonfinancial:'Неденежный результат'};
export default function Calculations({kind,draft,onChange}:{kind:ModelKind;draft:CalculationDraft;onChange:(x:CalculationDraft)=>void}){
 const [economic,setEconomic]=useState<CalculationResult|null>(null),[model,setModel]=useState<CalculationResult|null>(null),[benefitKind,setBenefitKind]=useState<Benefit['kind']>('cash_saving'),[benefitValue,setBenefitValue]=useState(''),[overlap,setOverlap]=useState(''),[error,setError]=useState('');
 const change=(x:Partial<CalculationDraft>)=>{onChange({...draft,...x});setEconomic(null);setModel(null);};
 const calculate=()=>{setEconomic(evaluateEconomics({currency:draft.currency,vat:draft.vat,mode:draft.mode,horizonYears:draft.horizon===''?undefined:Number(draft.horizon),inputs:measurements(economicFields,draft.inputs,draft.source,draft.currency),benefits:draft.benefits,benefitsConfirmed:draft.confirmed,annualAmountsConstant:draft.constant}));};
 return <><div className="notice"><strong>Сначала — данные объекта.</strong> Паспортные параметры и чужой кейс не заменяют измерения вашего процесса. Высвобождённое время учитывается отдельно от денежных выгод.</div><div className="two-column"><section className="panel"><span className="eyebrow">01 / Ресурсы процесса</span><h2>Проверка мощности</h2><label>Источник исходных данных<input value={draft.source} onChange={e=>change({source:e.target.value})} placeholder="Документ, версия, дата и раздел измерений"/><small>Ссылка или точный идентификатор документа; будет включён в trace.</small></label><Fields fields={modelFields[kind]} values={draft.modelInputs} onChange={(key,value)=>change({modelInputs:{...draft.modelInputs,[key]:value}})}/><button className="primary" onClick={()=>setModel(evaluateModel({kind,inputs:measurements(modelFields[kind],draft.modelInputs,draft.source)}))}>Рассчитать ресурсы</button></section><Results result={model} label="Ресурсы и мощность"/></div>
 <div className="two-column"><section className="panel"><span className="eyebrow">02 / Денежные потоки</span><h2>Экономика проекта</h2><div className="form-grid"><label>Модель приобретения<select value={draft.mode} onChange={e=>change({mode:e.target.value as CalculationDraft['mode']})}><option value="purchase">Покупка</option><option value="lease">Аренда</option><option value="subscription">Подписка</option></select></label><label>Валюта<input value={draft.currency} maxLength={3} onChange={e=>change({currency:e.target.value.toUpperCase()})}/></label><label>Учёт НДС<select value={draft.vat} onChange={e=>change({vat:e.target.value as CalculationDraft['vat']})}><option value="excluded">Все суммы без НДС</option><option value="included">Все суммы с НДС</option></select></label><label>Горизонт, лет<input type="number" min="1" max="100" value={draft.horizon} onChange={e=>change({horizon:e.target.value})}/></label></div><p className="muted">{draft.mode==='purchase'?'Включите всю конфигурацию и внедрение в первоначальные затраты.':'Первоначальные платежи включите в CAPEX, регулярные платежи — в годовой OPEX. Не переносите цену покупки в аренду.'}</p><Fields fields={economicFields} values={draft.inputs} currency={draft.currency} onChange={(key,value)=>change({inputs:{...draft.inputs,[key]:value}})}/>
 <h3>Реестр выгод</h3><p className="muted">Один ресурс или поток не должен учитываться дважды. Используйте общий ключ для одного источника эффекта.</p>{draft.benefits.map(b=><div className="saved-row" key={b.id}><div><strong>{benefitKinds[b.kind]}</strong><small>{number(b.value)} {b.unit} · {b.overlapKey}</small></div><button onClick={()=>change({benefits:draft.benefits.filter(x=>x.id!==b.id)})}>Удалить</button></div>)}<div className="form-grid"><label>Тип выгоды<select value={benefitKind} onChange={e=>setBenefitKind(e.target.value as Benefit['kind'])}>{Object.entries(benefitKinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Подтверждённая величина<input type="number" min="0" step="any" value={benefitValue} onChange={e=>setBenefitValue(e.target.value)}/><small>{benefitKind==='time_released'?'h/year':benefitKind==='nonfinancial'?'count':draft.currency+'/year'}</small></label></div><label>Ключ ресурса / потока<input value={overlap} onChange={e=>setOverlap(e.target.value)} placeholder="Идентификатор из реестра предприятия"/></label><button onClick={()=>{if(benefitValue===''||!overlap.trim()||!draft.source.trim()){setError('Нужны величина, ключ ресурса и источник данных.');return;}change({benefits:[...draft.benefits,{id:crypto.randomUUID(),kind:benefitKind,value:Number(benefitValue),unit:benefitKind==='time_released'?'h/year':benefitKind==='nonfinancial'?'count':draft.currency+'/year',sourceRef:draft.source,overlapKey:overlap}]});setBenefitValue('');setOverlap('');setError('');}}>Добавить выгоду</button>{error&&<p role="alert">{error}</p>}
 <label className="check"><input type="checkbox" checked={draft.confirmed} onChange={e=>change({confirmed:e.target.checked})}/>Реестр выгод проверен: подтверждён спрос для дополнительной маржи, исключён повторный учёт.</label><label className="check"><input type="checkbox" checked={draft.constant} onChange={e=>change({constant:e.target.checked})}/>Постоянные годовые суммы применимы на всём горизонте.</label><button className="primary" onClick={calculate}>Рассчитать экономику</button><details><summary>NPV и структурированный ввод</summary><p>Загрузите JSON по контракту модели: ставка discountRate и подтверждённые денежные потоки cashFlows за каждый год. Формат описан в документации моделей.</p><label className="upload">Загрузить экономический JSON<input type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>2_000_000)throw new Error('Файл больше 2 МБ');setEconomic(evaluateEconomics(JSON.parse(await f.text())));}catch(err){setError(String(err));}e.target.value='';}}/></label></details></section><Results result={economic} label="Прозрачная экономика"/></div></>;
}
