import {useEffect,useMemo,useRef,useState} from 'react';
import {Box,Building2,DoorOpen,Download,Hospital,ImageUp,Layers3,Plane,Play,RotateCcw,Square,Warehouse,Wrench,ZoomIn} from 'lucide-react';
import registry from '../../data/catalog.json';
import {createScenario,gridRoute,type Layout,type Sector,type SimulationInput} from '../../packages/ris/contracts';
import {applySceneTool,importSceneLayout} from '../../packages/ris/scene';
import {compareDigitalTwin,processPresets,runBaseline,runDigitalTwin,type TwinFinance,type TwinResult} from '../../packages/ris/digitalTwin';
import Scene3D from './Scene3D';
import './digital-twin.css';

type SceneKind='wall'|'rack'|'door'|'charger'|'station'|'elevator';
type SceneObject={id:string;kind:SceneKind;x:number;y:number;w:number;h:number;blocking:boolean;label:string;capacity:number};
type Tool='select'|'pickup'|'dropoff'|'wall'|'rack'|'door'|'charger'|'station'|'elevator'|'remove';
type Product=(typeof registry.products)[number];
const transport=registry.products.filter(p=>p.familyId==='transport');
const icons:Record<SceneKind,typeof Box>={wall:Square,rack:Layers3,door:DoorOpen,charger:Wrench,station:Box,elevator:Building2};
const blockingKinds=new Set<SceneKind>(['wall','rack']);
const financeDefaults:TwinFinance={robotUnitPrice:1900000,integration:400000,infrastructure:300000,maintenancePerRobotYear:120000,electricityPerKwh:9,baselineAnnualCost:5000000,residualHumanAnnualCost:900000,workdays:250,horizonYears:5,discountRatePercent:12,annualRequiredJobs:25000};
const fmt=(v:number,d=1)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:d}).format(v);
const rub=(v:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(v)+' ₽';
const getSpec=(product:Product|undefined,key:string)=>product?.characteristics.find(c=>c.key===key)?.value;
const objectsFrom=(layout:Layout):SceneObject[]=>layout.obstacles.map((o,i)=>({id:'base-'+i,kind:'rack',...o,blocking:true,label:'Стеллаж '+(i+1),capacity:1}));
const layoutFrom=(layout:Layout,objects:SceneObject[]):Layout=>({...layout,obstacles:objects.filter(o=>o.blocking).map(({x,y,w,h})=>({x,y,w,h}))});
const sectors:[Sector,string,typeof Warehouse][]=[['warehouse','Склад',Warehouse],['hospital','Медучреждение',Hospital],['airport','Аэропорт',Plane],['factory','Производство',Building2]];

export default function DigitalTwinStudio({initialScenario,initialRobotId,onScenario}:{initialScenario:SimulationInput;initialRobotId:string|null;onScenario?:(value:SimulationInput)=>void}){
 const [scenario,setScenarioState]=useState(()=>structuredClone(initialScenario));
 const [objects,setObjects]=useState<SceneObject[]>(()=>objectsFrom(initialScenario.layout));
 const [tool,setTool]=useState<Tool>('select'),[selectedObject,setSelectedObject]=useState<string|null>(null);
 const [planUrl,setPlanUrl]=useState<string|null>(null),[planName,setPlanName]=useState(''),[planStatus,setPlanStatus]=useState('План не загружен — используется параметрическая сцена.');
 const [robotId,setRobotId]=useState(initialRobotId&&transport.some(p=>p.id===initialRobotId)?initialRobotId:(transport[0]?.id??''));
 const [baselineWorkers,setBaselineWorkers]=useState(4),[baselineSpeed,setBaselineSpeed]=useState(1.1),[baselineService,setBaselineService]=useState(80);
 const [finance,setFinance]=useState<TwinFinance>(financeDefaults),[robotResult,setRobotResult]=useState<TwinResult|null>(null),[baselineResult,setBaselineResult]=useState<TwinResult|null>(null);
 const [frameIndex,setFrameIndex]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(8),[view,setView]=useState<'2d'|'3d'>('2d');
 const [cloudStatus,setCloudStatus]=useState<{configured:boolean;note:string}|null>(null),[error,setError]=useState('');
 const fileRef=useRef<HTMLInputElement>(null),dragRef=useRef<string|null>(null),svgRef=useRef<SVGSVGElement>(null);
 const route=useMemo(()=>gridRoute(scenario.layout),[scenario.layout]);
 const frame=robotResult?.frames[Math.min(frameIndex,Math.max(0,robotResult.frames.length-1))]??null;
 const assessment=robotResult&&baselineResult?compareDigitalTwin({scenario,baseline:baselineResult,robot:robotResult,finance}):null;
 const selectedScene=objects.find(o=>o.id===selectedObject)??null;
 const setScenario=(next:SimulationInput)=>{setScenarioState(next);onScenario?.(next);setRobotResult(null);setBaselineResult(null);setPlaying(false);setFrameIndex(0);};
 const patchScenario=(fn:(value:SimulationInput)=>SimulationInput)=>setScenario(fn(scenario));
 const syncObjects=(next:SceneObject[])=>{setObjects(next);const chargingChannels=next.filter(o=>o.kind==='charger').reduce((sum,o)=>sum+Math.max(1,o.capacity),0);patchScenario(s=>({...s,layout:layoutFrom(s.layout,next),robot:{...s.robot,...(chargingChannels>0?{chargerCount:chargingChannels}:{})}}));};
 useEffect(()=>{fetch('/api/v1/ris/cloud/status').then(r=>r.ok?r.json():{configured:false,note:'AnyLogic connector отключён в публичном preview.'}).then(x=>setCloudStatus(x)).catch(()=>setCloudStatus({configured:false,note:'AnyLogic connector недоступен.'}));},[]);
 useEffect(()=>{if(!playing||!robotResult)return;const id=window.setInterval(()=>setFrameIndex(i=>{if(i>=robotResult.frames.length-1){setPlaying(false);return i;}return i+1;}),Math.max(35,1000/speed));return()=>clearInterval(id);},[playing,robotResult,speed]);
 useEffect(()=>()=>{if(planUrl)URL.revokeObjectURL(planUrl);},[planUrl]);

 const coordinate=(event:React.PointerEvent<SVGSVGElement>)=>{const rect=svgRef.current?.getBoundingClientRect();if(!rect)return null;return{x:Math.max(0,Math.min(scenario.layout.width-1,Math.floor((event.clientX-rect.left)/rect.width*scenario.layout.width))),y:Math.max(0,Math.min(scenario.layout.height-1,Math.floor((event.clientY-rect.top)/rect.height*scenario.layout.height)))};};
 const place=(point:{x:number;y:number})=>{
  if(tool==='pickup'||tool==='dropoff'){const layout=applySceneTool(scenario.layout,tool,point);if(layout!==scenario.layout)setScenario({...scenario,layout});return;}
  if(tool==='remove'){const hit=objects.find(o=>point.x>=o.x&&point.x<o.x+o.w&&point.y>=o.y&&point.y<o.y+o.h);if(hit)syncObjects(objects.filter(o=>o.id!==hit.id));return;}
  if(tool==='select')return;
  const kind=tool as SceneKind,blocking=blockingKinds.has(kind);
  if(blocking&&[scenario.layout.pickup,scenario.layout.dropoff].some(p=>p.x===point.x&&p.y===point.y))return;
  const item:SceneObject={id:crypto.randomUUID(),kind,x:point.x,y:point.y,w:kind==='wall'?3:kind==='rack'?2:1,h:1,blocking,label:{wall:'Стена',rack:'Стеллаж',door:'Дверь',charger:'Зарядная станция',station:'Рабочая станция',elevator:'Лифт'}[kind],capacity:1};
  syncObjects([...objects,item]);setSelectedObject(item.id);
 };
 const pointerDown=(event:React.PointerEvent<SVGSVGElement>)=>{const point=coordinate(event);if(!point)return;const target=(event.target as SVGElement).closest('[data-scene-id]')?.getAttribute('data-scene-id');if(tool==='select'&&target){dragRef.current=target;setSelectedObject(target);event.currentTarget.setPointerCapture(event.pointerId);return;}place(point);};
 const pointerMove=(event:React.PointerEvent<SVGSVGElement>)=>{if(!dragRef.current)return;const point=coordinate(event);if(!point)return;const id=dragRef.current;const next=objects.map(o=>o.id===id?{...o,x:Math.min(point.x,scenario.layout.width-o.w),y:Math.min(point.y,scenario.layout.height-o.h)}:o);setObjects(next);setScenarioState(s=>({...s,layout:layoutFrom(s.layout,next)}));};
 const pointerUp=()=>{if(dragRef.current){dragRef.current=null;onScenario?.(scenario);setRobotResult(null);setBaselineResult(null);}};

 const loadFile=async(file:File)=>{
  setError('');
  if(file.size>20*1024*1024){setError('Файл больше 20 МБ. Для рабочего прототипа используйте облегчённый план.');return;}
  if(file.name.toLowerCase().endsWith('.json')){try{const layout=importSceneLayout(await file.text());setObjects(objectsFrom(layout));setScenario({...scenario,layout});setPlanName(file.name);setPlanStatus('Геометрия импортирована из JSON и проверена.');}catch(e){setError(e instanceof Error?e.message:'Не удалось импортировать геометрию.');}return;}
  if(file.type.startsWith('image/')){if(planUrl)URL.revokeObjectURL(planUrl);setPlanUrl(URL.createObjectURL(file));setPlanName(file.name);setPlanStatus('Растровый план добавлен как масштабируемая подложка. Обведите рабочую геометрию инструментами редактора.');return;}
  setPlanName(file.name);setPlanStatus('PDF/CAD прикреплён как исходный документ. Автоматический векторный импорт в этой сборке не выполняется — геометрию нужно перенести в сцену вручную или через отдельный импортёр.');
 };
 const chooseSector=(sector:Sector)=>{const next=createScenario(sector);setObjects(objectsFrom(next.layout));setScenario(next);setPlanUrl(null);setPlanName('');setPlanStatus('Загружен отраслевой шаблон: '+processPresets[sector].task+'.');};
 const chooseRobot=(id:string)=>{setRobotId(id);const product=transport.find(p=>p.id===id),payload=getSpec(product,'payload'),maxSpeed=getSpec(product,'max_speed');patchScenario(s=>({...s,robot:{...s.robot,...(typeof payload==='number'?{payloadKg:payload}:{}),...(typeof maxSpeed==='number'?{speedMps:Math.min(maxSpeed,s.robot.speedMps)}:{})}}));};
 const run=()=>{try{setError('');const robot=runDigitalTwin({scenario,robotId,frameStepSeconds:2});const baseline=runBaseline({scenario,workers:baselineWorkers,speedMps:baselineSpeed,serviceSeconds:baselineService,frameStepSeconds:4});setRobotResult(robot);setBaselineResult(baseline);setFrameIndex(0);setPlaying(true);}catch(e){setError(e instanceof Error?e.message:'Не удалось выполнить модель.');}};
 const reset=()=>{const next=createScenario(scenario.sector);setObjects(objectsFrom(next.layout));setScenario(next);setRobotResult(null);setBaselineResult(null);setPlanUrl(null);setPlanName('');setPlanStatus('Шаблон восстановлен.');};
 const saveProject=()=>{const data={version:4,kind:'ris-digital-twin',scenario,objects,robotId,baseline:{workers:baselineWorkers,speedMps:baselineSpeed,serviceSeconds:baselineService},finance,robotResult,baselineResult,assessment};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='ris-digital-twin.json';a.click();URL.revokeObjectURL(a.href);};
 const chart=robotResult?.timeline??[],maxY=Math.max(1,...chart.map(x=>Math.max(x.created,x.completed,x.backlog))),chartPoints=(key:'completed'|'backlog')=>chart.map((p,i)=>(chart.length<=1?0:i/(chart.length-1)*100)+','+(44-(p[key]/maxY)*40)).join(' ');

 return <section className="dt-root">
  <div className="dt-hero"><div><span>DIGITAL TWIN STUDIO / BETA</span><h1>Помещение → движение → <em>экономика</em></h1><p>Редактируйте рабочую сцену, запускайте одинаковую нагрузку через исходный и роботизированный процесс и проверяйте результат по сохранённым траекториям.</p></div><div className="dt-engine"><b>Движок</b><strong>RIS Digital Twin · grid-agv/1.0</strong><small>{cloudStatus?.configured?'AnyLogic connector настроен; модель должна пройти инспекцию перед использованием.':'AnyLogic: '+(cloudStatus?.note??'проверка подключения…')}</small></div></div>
  <div className="dt-steps"><span className="active">01 План</span><span>02 Объекты</span><span>03 Процесс и парк</span><span>04 Исполнение</span><span>05 Сравнение и ROI</span></div>

  <div className="dt-top-grid"><article className="dt-card"><div className="dt-title"><ImageUp size={19}/><h3>1. Загрузка помещения</h3></div><input ref={fileRef} hidden type="file" accept=".png,.jpg,.jpeg,.webp,.pdf,.dxf,.dwg,.json" onChange={e=>e.target.files?.[0]&&loadFile(e.target.files[0])}/><button className="dt-upload" onClick={()=>fileRef.current?.click()}><ImageUp size={17}/> Загрузить PNG / JPG / PDF / CAD / JSON</button><b>{planName||'Новый объект'}</b><p>{planStatus}</p><div className="dt-dimensions"><label>Ширина, м<input type="number" min="8" max="300" value={scenario.layout.width} onChange={e=>patchScenario(s=>({...s,layout:{...s.layout,width:Math.max(8,Math.min(300,Number(e.target.value)))}}))}/></label><label>Высота, м<input type="number" min="8" max="300" value={scenario.layout.height} onChange={e=>patchScenario(s=>({...s,layout:{...s.layout,height:Math.max(8,Math.min(300,Number(e.target.value)))}}))}/></label></div>
  <div className="dt-sector-row">{sectors.map(([id,label,Icon])=><button key={id} className={scenario.sector===id?'selected':''} onClick={()=>chooseSector(id)}><Icon size={16}/>{label}</button>)}</div></article>
  <article className="dt-card"><div className="dt-title"><Wrench size={19}/><h3>3. Процесс и оборудование</h3></div><strong className="dt-process">{processPresets[scenario.sector].task}</strong><label>Модель робота<select value={robotId} onChange={e=>chooseRobot(e.target.value)}>{transport.map(p=><option key={p.id} value={p.id}>{p.vendor} · {p.name}</option>)}</select></label><div className="dt-fields"><label>Роботов<input type="number" min="1" max="100" value={scenario.robot.count} onChange={e=>patchScenario(s=>({...s,robot:{...s.robot,count:Number(e.target.value)}}))}/></label><label>Скорость, м/с<input type="number" step=".05" min=".05" value={scenario.robot.speedMps} onChange={e=>patchScenario(s=>({...s,robot:{...s.robot,speedMps:Number(e.target.value)}}))}/></label><label>Заданий/ч<input type="number" min=".1" value={scenario.workload.demandPerHour} onChange={e=>patchScenario(s=>({...s,workload:{...s.workload,demandPerHour:Number(e.target.value)}}))}/></label><label>Смена, ч<input type="number" step=".25" min=".25" value={scenario.workload.shiftHours} onChange={e=>patchScenario(s=>({...s,workload:{...s.workload,shiftHours:Number(e.target.value)}}))}/></label></div><small>Паспортные характеристики из каталога используются только там, где есть подтверждённое численное поле. Эксплуатационные параметры остаются редактируемыми.</small></article></div>

  <div className="dt-editor-shell"><div className="dt-editor-head"><div><b>2. Редактор 2D</b><span>{scenario.layout.width} × {scenario.layout.height} м · сетка 1 м</span></div><div className="dt-view-toggle"><button className={view==='2d'?'active':''} onClick={()=>setView('2d')}>2D</button><button className={view==='3d'?'active':''} onClick={()=>setView('3d')}>3D</button></div></div>
   <div className="dt-toolbar">{([{id:'select',label:'Выбор'},{id:'wall',label:'Стена'},{id:'rack',label:'Стеллаж'},{id:'door',label:'Дверь'},{id:'charger',label:'Зарядка'},{id:'station',label:'Станция'},{id:'elevator',label:'Лифт'},{id:'pickup',label:'Старт A'},{id:'dropoff',label:'Финиш B'},{id:'remove',label:'Удалить'}] as {id:Tool;label:string}[]).map(x=><button key={x.id} className={tool===x.id?'active':''} onClick={()=>setTool(x.id)}>{x.label}</button>)}<button onClick={reset}><RotateCcw size={14}/> Сброс</button></div>
   <div className="dt-editor-body"><div className="dt-canvas-wrap">{view==='2d'?<svg ref={svgRef} className="dt-floor" viewBox={'0 0 '+scenario.layout.width+' '+scenario.layout.height} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}>
    {planUrl&&<image href={planUrl} x="0" y="0" width={scenario.layout.width} height={scenario.layout.height} preserveAspectRatio="none" opacity=".34"/>}
    <defs><pattern id="dt-grid" width="1" height="1" patternUnits="userSpaceOnUse"><path d="M 1 0 L 0 0 0 1" fill="none" stroke="#b7c3cb" strokeWidth=".05"/></pattern></defs><rect width="100%" height="100%" fill={planUrl?'transparent':'#eef2f4'}/><rect width="100%" height="100%" fill="url(#dt-grid)"/>
    {route&&<polyline points={route.points.map(p=>(p.x+.5)+','+(p.y+.5)).join(' ')} fill="none" stroke="#3178f5" strokeWidth=".35" strokeDasharray=".7 .35"/>}
    {objects.map(o=>{const Icon=icons[o.kind];return <g key={o.id} data-scene-id={o.id} onClick={()=>setSelectedObject(o.id)}><rect x={o.x} y={o.y} width={o.w} height={o.h} rx=".12" className={'dt-obj '+o.kind+(selectedObject===o.id?' selected':'')}/><foreignObject x={o.x} y={o.y} width={Math.max(1,o.w)} height={Math.max(1,o.h)} pointerEvents="none"><div className="dt-obj-icon"><Icon size={10}/></div></foreignObject></g>})}
    <g><circle cx={scenario.layout.pickup.x+.5} cy={scenario.layout.pickup.y+.5} r=".65" className="dt-a"/><text x={scenario.layout.pickup.x+.5} y={scenario.layout.pickup.y+.75} textAnchor="middle">A</text></g><g><circle cx={scenario.layout.dropoff.x+.5} cy={scenario.layout.dropoff.y+.5} r=".65" className="dt-b"/><text x={scenario.layout.dropoff.x+.5} y={scenario.layout.dropoff.y+.75} textAnchor="middle">B</text></g>
    {frame?.robots.map(r=><g key={r.id}><circle cx={r.x} cy={r.y} r=".55" className={'dt-robot-dot '+r.state}/><text x={r.x} y={r.y+.18} textAnchor="middle" className="dt-robot-text">{r.id.replace('R','')}</text></g>)}
   </svg>:<Scene3D layout={scenario.layout} robots={(frame?.robots??[]).map(r=>({id:r.id,x:r.x,y:r.y}))}/>}</div>
   <aside className="dt-inspector"><span>СВОЙСТВА ОБЪЕКТА</span>{selectedScene?<><strong>{selectedScene.label}</strong><label>Название<input value={selectedScene.label} onChange={e=>{const next=objects.map(o=>o.id===selectedScene.id?{...o,label:e.target.value}:o);setObjects(next);}}/></label><label>Вместимость / каналы<input type="number" min="1" value={selectedScene.capacity} onChange={e=>syncObjects(objects.map(o=>o.id===selectedScene.id?{...o,capacity:Number(e.target.value)}:o))}/></label><small>{selectedScene.blocking?'Объект блокирует движение робота.':'Объект не блокирует сетку; его технологическая логика подключается через сценарий.'}</small></>:<p>Выберите объект или инструмент. В режиме «Выбор» элементы можно перетаскивать.</p>}<div className="dt-legend"><i className="rack"/> препятствие<i className="charger"/> инфраструктура<i className="robot"/> робот</div></aside></div>
  </div>

  <div className="dt-run-grid"><article className="dt-card"><div className="dt-title"><Play size={19}/><h3>4. Исполнение модели</h3></div><div className="dt-baseline"><b>Исходный процесс</b><div className="dt-fields"><label>Исполнителей<input type="number" min="1" value={baselineWorkers} onChange={e=>setBaselineWorkers(Number(e.target.value))}/></label><label>Скорость, м/с<input type="number" step=".1" value={baselineSpeed} onChange={e=>setBaselineSpeed(Number(e.target.value))}/></label><label>Обслуживание, с<input type="number" value={baselineService} onChange={e=>setBaselineService(Number(e.target.value))}/></label></div></div><button className="dt-run" onClick={run} disabled={!route||!robotId}><Play size={17}/> Запустить одинаковую нагрузку</button>{error&&<p role="alert" className="dt-error">{error}</p>}<p className="dt-proof">Анимация строится из кадров, созданных тем же запуском, из которого берутся KPI. Независимое декоративное движение не генерируется.</p></article>
  <article className="dt-card dt-kpis"><div className="dt-title"><ZoomIn size={19}/><h3>Результат сценария</h3></div>{robotResult?<><div className="dt-kpi-grid"><div><small>Выполнено</small><strong>{robotResult.completed}/{robotResult.created}</strong></div><div><small>Производительность</small><strong>{fmt(robotResult.throughputPerHour,2)}/ч</strong></div><div><small>Очередь</small><strong>{fmt(robotResult.meanQueueMinutes,2)} мин</strong></div><div><small>P95 задания</small><strong>{robotResult.p95JobSeconds==null?'—':fmt(robotResult.p95JobSeconds,0)+' с'}</strong></div><div><small>Загрузка парка</small><strong>{fmt(robotResult.robotUtilization*100,1)}%</strong></div><div><small>Энергия</small><strong>{fmt(robotResult.energyKwh,2)} кВт·ч</strong></div><div><small>Ожидание трафика</small><strong>{robotResult.trafficWaitSeconds} с</strong></div><div><small>Остаток</small><strong>{robotResult.backlog}</strong></div></div><svg className="dt-chart" viewBox="0 0 100 48" preserveAspectRatio="none"><line x1="0" y1="44" x2="100" y2="44"/><polyline className="completed" points={chartPoints('completed')}/><polyline className="backlog" points={chartPoints('backlog')}/></svg><div className="dt-chart-legend"><span>выполнено</span><span>очередь</span></div></>:<div className="dt-empty">Результаты появятся после запуска модели.</div>}</article></div>

  {robotResult&&<div className="dt-replay"><button onClick={()=>setPlaying(v=>!v)}>{playing?'Пауза':'Воспроизвести'}</button><input aria-label="Время симуляции" type="range" min="0" max={Math.max(0,robotResult.frames.length-1)} value={frameIndex} onChange={e=>{setPlaying(false);setFrameIndex(Number(e.target.value));}}/><b>{frame?Math.floor(frame.t/60)+' мин '+frame.t%60+' с':'0 с'}</b><label>Скорость<select value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value="1">1×</option><option value="4">4×</option><option value="8">8×</option><option value="20">20×</option></select></label></div>}

  <div className="dt-economy"><div className="dt-econ-head"><div><span>5. Сравнение и экономика</span><h2>Одинаковая работа. Два способа выполнения.</h2></div><button onClick={saveProject}><Download size={16}/> Экспорт проекта и траекторий</button></div>
   <div className="dt-compare">{baselineResult&&robotResult?<><div><small>ИСХОДНЫЙ ПРОЦЕСС</small><strong>{baselineResult.completed} задач/смену</strong><span>{fmt(baselineResult.meanQueueMinutes,2)} мин средняя очередь</span><span>{fmt(baselineResult.robotUtilization*100,1)}% загрузка ресурсов</span></div><div><small>РОБОТИЗИРОВАННЫЙ</small><strong>{robotResult.completed} задач/смену</strong><span>{fmt(robotResult.meanQueueMinutes,2)} мин средняя очередь</span><span>{fmt(robotResult.robotUtilization*100,1)}% загрузка парка</span></div></>:<p>Сначала выполните оба сценария одним запуском.</p>}</div>
   <div className="dt-finance-grid"><label>Цена робота, ₽<input type="number" value={finance.robotUnitPrice} onChange={e=>setFinance({...finance,robotUnitPrice:Number(e.target.value)})}/></label><label>Интеграция, ₽<input type="number" value={finance.integration} onChange={e=>setFinance({...finance,integration:Number(e.target.value)})}/></label><label>Инфраструктура, ₽<input type="number" value={finance.infrastructure} onChange={e=>setFinance({...finance,infrastructure:Number(e.target.value)})}/></label><label>ТО одного робота/год, ₽<input type="number" value={finance.maintenancePerRobotYear} onChange={e=>setFinance({...finance,maintenancePerRobotYear:Number(e.target.value)})}/></label><label>Текущий процесс/год, ₽<input type="number" value={finance.baselineAnnualCost} onChange={e=>setFinance({...finance,baselineAnnualCost:Number(e.target.value)})}/></label><label>Остающийся человеческий OPEX, ₽<input type="number" value={finance.residualHumanAnnualCost} onChange={e=>setFinance({...finance,residualHumanAnnualCost:Number(e.target.value)})}/></label><label>Требуется задач/год<input type="number" value={finance.annualRequiredJobs} onChange={e=>setFinance({...finance,annualRequiredJobs:Number(e.target.value)})}/></label></div>
   <div className="dt-investment"><div><small>CAPEX</small><strong>{assessment?rub(assessment.capex):'—'}</strong></div><div><small>OPEX/год</small><strong>{assessment?rub(assessment.annualOpex):'—'}</strong></div><div><small>ROI · {finance.horizonYears} лет</small><strong>{assessment?.roiPercent==null?'Заблокирован':fmt(assessment.roiPercent,1)+'%'}</strong></div><div><small>Окупаемость</small><strong>{assessment?.paybackYears==null?'—':fmt(assessment.paybackYears,2)+' года'}</strong></div><div><small>NPV</small><strong>{assessment?.npv==null?'—':rub(assessment.npv)}</strong></div></div>{assessment?.warnings.map(x=><p key={x} className="dt-warning">{x}</p>)}
  </div>
 </section>;
}
