import {useEffect,useState} from 'react';
import {replaySimulation,simulateFlow,snapshotSimulation,type SimulationResult,type ModelKind} from '../../packages/domain';
import {Play,Pause,RotateCcw,Upload,FileText,Activity} from 'lucide-react';
import {Results} from './Calculations';
import {download,number} from './utils';
import ObservedLog from './ObservedLog';
const states:Record<string,string>={unknown:'Нет наблюдения',idle:'Ожидание',moving:'Перемещение',working:'Работа',charging:'Зарядка',maintenance:'Обслуживание',error:'Ошибка'};
export default function Simulation({kind}:{kind:ModelKind}){
 const [result,setResult]=useState<SimulationResult|null>(null),[mode,setMode]=useState('replay'),[error,setError]=useState(''),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[speed,setSpeed]=useState(1);
 const duration=result?.durationSeconds??0;const start=result?.observationStartSeconds??0;
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setTime(t=>{if(t+speed/10>=duration){setPlaying(false);return duration;}return t+speed/10;}),100);return()=>clearInterval(timer);},[playing,speed,duration]);
 const snapshot=result?snapshotSimulation(result,start+time):null;
 return <>{kind==='digital'&&<ObservedLog/>}<div className="notice"><strong>{mode==='replay'?'Воспроизведение наблюдений':'Модель очереди по реальным заданиям'}.</strong> {mode==='replay'?'Пробелы в журнале остаются неизвестными.':'FCFS на непрерывно доступных ресурсах. Поступления и время обслуживания загружаются из измерений.'} Это модель процесса, не физическая верификация объекта.</div><section className="panel"><div className="section-head"><div><span className="eyebrow">Сценарий / {kind==='digital'?'Цифровой поток':kind==='coverage'?'Уборка и покрытие':'Операции и ресурсы'}</span><h2>Процесс во времени</h2></div><select aria-label="Режим имитации" value={mode} onChange={e=>{setMode(e.target.value);setResult(null);setTime(0);setPlaying(false);}}><option value="replay">Журнал наблюдений</option><option value="flow">Расчёт очереди FCFS</option></select></div>
 {!result&&<div className="empty simulation-empty"><div className="diagram-icon">{kind==='digital'?<FileText size={40}/>:<Activity size={40}/>}</div><h3>Загрузите события вашего процесса</h3><p>Для временной модели нужны отметки поступления и длительности операций. Агрегатных показателей достаточно только для расчёта мощности на предыдущем шаге.</p></div>}
 <label className="upload"><Upload size={17}/> Загрузить JSON событий<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setPlaying(false);setTime(0);try{if(file.size>2_000_000)throw new Error('Максимальный размер — 2 МБ');const raw=JSON.parse(await file.text());setResult(mode==='replay'?replaySimulation(raw):simulateFlow(raw));setError('');}catch(err){setError(String(err));}e.target.value='';}}/></label>{error&&<p role="alert" className="errors">{error}</p>}
 {result?.status==='complete'&&<><div className="player"><button aria-label={playing?'Пауза':'Воспроизвести'} onClick={()=>{if(time>=duration)setTime(0);setPlaying(!playing);}}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><button aria-label="В начало" onClick={()=>{setTime(0);setPlaying(false);}}><RotateCcw size={18}/></button><input aria-label="Момент времени" type="range" min="0" max={duration} step="any" value={time} onChange={e=>{setTime(Number(e.target.value));setPlaying(false);}}/><span>{number(time)} / {number(duration)} с</span><select aria-label="Скорость воспроизведения" value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[1,10,60,600].map(v=><option key={v} value={v}>{v}×</option>)}</select></div><div className="live-kpis"><div><small>Завершённые операции</small><strong>{number(snapshot?.completedOperations)}</strong></div><div><small>Время от начала окна, с</small><strong>{number(time)}</strong></div><div><small>Происхождение</small><strong>{mode==='replay'?'Журнал':'Расчёт FCFS'}</strong></div></div>
 <div className={'process-view '+kind}>{Object.entries(snapshot?.states??{}).map(([id,state])=><div className={'resource '+state} key={id}><span className="resource-node">{kind==='digital'?<FileText/>:<Activity/>}</span><strong>{id}</strong><span>{states[state]??state}</span></div>)}</div><div className="timeline">{result.resources.map(id=><div className="timeline-row" key={id}><strong>{id}</strong><div className="track">{result.timeline.filter(e=>e.resourceId===id).map(e=><span key={e.id} className={'segment '+e.state} title={e.id+' · '+states[e.state]+' · '+number(e.endedAtSeconds-e.startedAtSeconds)+' с'} style={{left:Math.max(0,(e.startedAtSeconds-start)/duration*100)+'%',width:Math.min(100-(e.startedAtSeconds-start)/duration*100,(e.endedAtSeconds-e.startedAtSeconds)/duration*100)+'%'}}/>)}<i style={{left:time/duration*100+'%'}}/></div></div>)}</div><button onClick={()=>download('simulation.json',JSON.stringify(result,null,2))}>Скачать модель и происхождение</button></>}
 <details><summary>Контракт журнала и требования</summary><p>Каждая величина передаётся как value, unit, sourceRef. Временная единица — s. resources содержат id и sourceRef. Обязательно задайте observationStartSeconds и observationEndSeconds.</p><p>Для наблюдений: events с id, resourceId, state, startedAtSeconds, endedAtSeconds, при наличии — completedOperations (count). Для FCFS: arrivals с id, arrivedAtSeconds, serviceSeconds и continuousAvailabilityConfirmed: true. Синтетические примеры не подставляются.</p></details></section>{result&&<Results result={result} label="Результаты модели"/>}</>;
}
