import {useMemo,useRef,useState} from 'react';
import {ArrowRight,ArrowUpRight,BarChart3,Box,Check,ChevronRight,Download,Factory,FileText,HeartPulse,Info,MapPinned,Plane,Play,RotateCcw,Search,Settings2,ShieldAlert,ShoppingBag,Warehouse} from 'lucide-react';
import registry from '../../data/catalog.json';
import {createScenario,evaluateExperimentInvestment,experimentResultSchema,gridRoute,sectorTemplates,simulationSchema,type ExperimentResult,type FinanceInput,type MetricSummary,type Sector,type SimulationInput,type SimulationResult} from '../../packages/ris/contracts';
import './studio.css';

type Screen='welcome'|'object'|'market'|'layout'|'simulation'|'finance'|'report';
type Product=(typeof registry.products)[number];
const sectors:[Sector,typeof Warehouse][]=[['warehouse',Warehouse],['factory',Factory],['hospital',HeartPulse],['airport',Plane]];
const flow:[Screen,string,typeof Box][]=[['object','Объект',Box],['market','Маркетплейс',ShoppingBag],['layout','Планировка',MapPinned],['simulation','Симуляция',Play],['finance','Экономика',BarChart3],['report','Результат',FileText]];
const currency=(value:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(value)+' ₽';
const numeric=(value:number,digits=1)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:digits}).format(value);
const interval=(metric:MetricSummary,digits=1,suffix='',scale=1)=>metric.mean==null?'—':metric.samples>1?`${numeric(metric.mean*scale,digits)}${suffix} · 95% [${numeric((metric.low95??metric.mean)*scale,digits)}–${numeric((metric.high95??metric.mean)*scale,digits)}]`:`${numeric(metric.mean*scale,digits)}${suffix}`;
const initialFinance:FinanceInput={unitPrice:0,installation:0,infrastructure:0,chargersCost:0,maintenanceAnnual:0,electricityPerKwh:0,baselineCostAnnual:0,residualHumanCostAnnual:0,daysPerYear:250,horizonYears:5,discountRatePercent:15,annualDemand:0,baselineAnnualCompleted:0};
const getCharacteristic=(p:Product,key:string)=>p.characteristics.find(c=>c.key===key)?.value;
const sourceFor=(p:Product)=>registry.sources.filter(s=>p.sourceIds.includes(s.id));
function download(name:string,data:unknown){const href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=href;a.download=name;a.click();URL.revokeObjectURL(href);}
export default function Studio(){
 const [screen,setScreen]=useState<Screen>('welcome'),[scenario,setScenario]=useState<SimulationInput>(()=>createScenario('warehouse')),[selected,setSelected]=useState<string|null>(null);
 const [finance,setFinance]=useState<FinanceInput>(initialFinance),[result,setResult]=useState<SimulationResult|null>(null),[experiment,setExperiment]=useState<ExperimentResult|null>(null),[replications,setReplications]=useState(1),[running,setRunning]=useState(false),[error,setError]=useState('');
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[grabbed,setGrabbed]=useState<'pickup'|'dropoff'|null>(null);
 const canvasRef=useRef<SVGSVGElement>(null),generationRef=useRef(0),chosen=registry.products.find(p=>p.id===selected)??null;
 const route=useMemo(()=>gridRoute(scenario.layout),[scenario.layout]),valid=simulationSchema.safeParse(scenario).success;
 const estimate=useMemo(()=>{if(!experiment)return null;try{return evaluateExperimentInvestment(scenario,experiment,finance);}catch{return null;}},[scenario,experiment,finance]);
 const setTab=(s:Screen)=>{setScreen(s);setError('');window.scrollTo({top:0,behavior:'instant'});};
 const change=(update:(prev:SimulationInput)=>SimulationInput)=>{generationRef.current++;setScenario(old=>update(old));setResult(null);setExperiment(null);setRunning(false);setError('');};
 const field=(key:keyof SimulationInput['workload'],value:number)=>change(old=>({...old,workload:{...old.workload,[key]:value}}));
 const robotField=(key:keyof SimulationInput['robot'],value:number)=>change(old=>({...old,robot:{...old.robot,[key]:value}}));
 const financeField=(key:keyof FinanceInput,value:number)=>setFinance(old=>({...old,[key]:value}));
 const setExperimentReplications=(value:number)=>{generationRef.current++;setReplications(Math.max(1,Math.min(100,Math.trunc(value||1))));setResult(null);setExperiment(null);setRunning(false);setError('');};
 const chooseSector=(value:Sector)=>{generationRef.current++;setScenario(createScenario(value));setSelected(null);setResult(null);setExperiment(null);setReplications(1);setRunning(false);setFinance(initialFinance);setTab('object');};
 const chooseProduct=(product:Product)=>{if(product.familyId!=='transport')return;generationRef.current++;setResult(null);setExperiment(null);setRunning(false);setSelected(product.id);const payload=getCharacteristic(product,'payload');if(typeof payload==='number'&&payload>0)robotField('payloadKg',payload);setTab('layout');};
 const onMove=(event:React.PointerEvent<SVGSVGElement>)=>{if(!grabbed)return;const rect=canvasRef.current?.getBoundingClientRect();if(!rect)return;const x=Math.max(0,Math.min(scenario.layout.width-1,Math.floor((event.clientX-rect.left)/rect.width*scenario.layout.width)));const y=Math.max(0,Math.min(scenario.layout.height-1,Math.floor((event.clientY-rect.top)/rect.height*scenario.layout.height)));change(old=>({...old,layout:{...old.layout,[grabbed]:{x,y}}}));};
 async function execute(){const generation=++generationRef.current;setRunning(true);setError('');setResult(null);setExperiment(null);try{const res=await fetch('/api/v1/ris/experiment',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({scenario,replications})});const body=await res.json();if(generationRef.current!==generation)return;if(!res.ok)throw new Error(body.error??'Ошибка серии экспериментов');const compatible=experimentResultSchema.safeParse(body);if(!compatible.success)throw new Error('Несовместимый или неполный ответ вычислительного сервиса: проверьте версию SimPy и перезапустите сервис.');const next=compatible.data as ExperimentResult;setExperiment(next);setResult(next.runs[0]??null);}catch(e){if(generationRef.current===generation)setError(e instanceof Error?e.message:'Сервис недоступен');}finally{if(generationRef.current===generation)setRunning(false);}}

 return <div className="ris-site">
  <header className="ris-global"><button className="ris-wordmark" onClick={()=>setTab('welcome')} aria-label="Robot Investment Studio"><b>RIS<span>↗</span></b><small>ROBOT<br/>INVESTMENT<br/>STUDIO</small></button>
   <nav aria-label="Навигация платформы"><button onClick={()=>setTab('welcome')}>Продукт</button><button onClick={()=>setTab('object')}>Оценить проект</button><button onClick={()=>setTab('market')}>Маркетплейс</button><button onClick={()=>setTab('simulation')}>Моделирование</button></nav>
   <button className="ris-top-action" onClick={()=>setTab('object')}>Создать проект <ArrowUpRight size={18}/></button></header>
  {screen==='welcome'?<main className="ris-home">
   <section className="ris-home-hero"><div className="ris-hero-info"><div className="ris-eyebrow"><span/> ЦИФРОВОЙ ИНСТРУМЕНТ ОЦЕНКИ РОБОТИЗАЦИИ</div>
    <h1>А ЕСЛИ<br/><em>РОБОТ?</em></h1><p className="ris-home-lead">Проверьте идею роботизации до инвестиций.</p>
    <p className="ris-sub">Планировка объекта, реальные роботизированные решения, модель работы и прозрачный расчёт экономики — в одном проекте.</p>
    <div className="ris-actions"><button className="ris-primary" onClick={()=>setTab('object')}>Оценить роботизацию <ArrowUpRight size={21}/></button><button className="ris-secondary" onClick={()=>setTab('simulation')}><Play size={17}/> Открыть студию</button></div>
    <p className="ris-disclaimer"><ShieldAlert size={16}/> Предынвестиционная оценка. Результаты зависят от полноты исходных данных.</p>
   </div><div className="ris-hero-art" aria-hidden="true"><div className="ris-hero-blue"/><img src="/industrial-arm.svg" alt=""/><span className="ris-art-index">01 / МОДЕЛИРУЙ · СЧИТАЙ · СРАВНИВАЙ</span></div></section>
   <section className="ris-home-how"><div><span className="ris-mini-label">ОТ ВОПРОСА К ЦИФРАМ</span><h2>Не обещать.<br/><em>Проверять.</em></h2></div>{flow.slice(0,4).map(([key,name],index)=><button key={key} onClick={()=>setTab(key)}><b>0{index+1}</b><ArrowUpRight size={23}/><strong>{name}</strong><span>{['Параметры реального объекта','Подбор по характеристикам','Маршруты и инфраструктура','Очереди, задания и энергия'][index]}</span></button>)}</section>
   <section className="ris-industries"><div><span className="ris-mini-label">С ЧЕГО НАЧАТЬ</span><h2>Выберите ваш объект.</h2><p>Типовые планировки демонстрационные. Для оценки реальной площадки замените их измерениями.</p></div><div className="ris-industry-grid">{sectors.map(([key,Icon])=><button key={key} onClick={()=>chooseSector(key)}><Icon size={29}/><strong>{sectorTemplates[key].title}</strong><span>{sectorTemplates[key].subtitle}</span><ArrowUpRight className="ris-industry-arrow" size={19}/></button>)}</div></section>
   <section className="ris-home-last"><span className="ris-mini-label">ОДИН ПРОЕКТ · ВЕСЬ ПУТЬ</span><h2>От площадки<br/>к <em>обоснованию.</em></h2><button className="ris-primary" onClick={()=>setTab('object')}>Создать проект <ArrowUpRight/></button></section></main>:
   <div className="ris-workspace"><aside className="ris-side"><div className="ris-side-kicker">РАБОЧЕЕ ПРОСТРАНСТВО / 01</div><h2>Модель<br/>объекта.</h2><div className="ris-side-context"><span className="ris-status-dot"/> {sectorTemplates[scenario.sector].title}<small>Транспортная операция · демонстрационный шаблон</small></div>
    <nav aria-label="Этапы проекта">{flow.map(([key,label,Icon],i)=><button key={key} className={screen===key?'active':''} onClick={()=>setTab(key)}><span className="ris-nav-index">0{i+1}</span><Icon size={18}/><strong>{label}</strong><ChevronRight size={16}/></button>)}</nav>
    <div className="ris-side-end"><Info size={18}/> Физическая проходимость, безопасность и точность паспортных характеристик требуют инженерной проверки.</div></aside>
    <main className="ris-content"><div className="ris-content-top"><span>RIS / PROJECT STUDIO</span><div><span className="ris-project-pill">{result?'Результат моделирования получен':'Оценка · исходные данные'}</span><button onClick={()=>download('ris-project.json',{version:2,scenario,selected,finance,replications,result,experiment,estimate})}><Download size={16}/> Экспорт проекта</button></div></div>

     {screen==='object'&&<><div className="ris-page-heading"><span className="ris-mini-label">ЭТАП 01 / КОНТЕКСТ</span><h1>Что будем<br/><em>роботизировать?</em></h1><p>Начните с задачи и реального объёма работ. Шаблоны ниже — демонстрационные, а не модель вашего предприятия.</p></div>
      <div className="ris-work-card"><h3>01. Тип объекта</h3><div className="ris-type-grid">{sectors.map(([key,Icon])=><button key={key} className={scenario.sector===key?'selected':''} onClick={()=>chooseSector(key)}><Icon size={28}/><strong>{sectorTemplates[key].title}</strong><small>{sectorTemplates[key].operation}</small>{scenario.sector===key&&<Check size={20}/>}</button>)}</div></div>
      <div className="ris-work-card ris-card-split"><div><span className="ris-mini-label">02 / ОПЕРАЦИЯ</span><h3>{sectorTemplates[scenario.sector].subtitle}</h3><p>Первая модель — транспортировка между двумя точками в пределах одного уровня. Это не полноценная модель всех операций предприятия.</p></div>
       <div className="ris-fields"><label>Заданий в час <input aria-label="Заданий в час" type="number" min=".1" value={scenario.workload.demandPerHour} onChange={e=>field('demandPerHour',Number(e.target.value))}/></label>
       <label>Масса одного груза, кг <input aria-label="Масса груза" type="number" min=".1" value={scenario.workload.loadKg} onChange={e=>field('loadKg',Number(e.target.value))}/></label>
       <label>Часов в смену <input aria-label="Часов в смену" type="number" min=".25" max="24" value={scenario.workload.shiftHours} onChange={e=>field('shiftHours',Number(e.target.value))}/></label></div></div>
      <div className="ris-next"><span>Следующий этап: технический подбор оборудования</span><button className="ris-primary" onClick={()=>setTab('market')}>Перейти к роботам <ArrowRight size={19}/></button></div></>}
     {screen==='market'&&<><div className="ris-page-heading"><span className="ris-mini-label">ЭТАП 02 / КАТАЛОГ</span><h1>Роботы.<br/><em>Не обещания.</em></h1><p>Независимый справочник с первичными источниками. Полнота характеристик, коммерческие цены и готовность к моделированию проверяются отдельно.</p></div>
      <div className="ris-market-controls"><label><Search size={18}/><input aria-label="Поиск роботов" placeholder="Модель, производитель, задача..." value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Категория оборудования" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Все категории</option>{[...new Set(registry.products.map(p=>p.familyId))].map(k=><option key={k} value={k}>{k}</option>)}</select><span>{registry.products.filter(p=>(filter==='all'||filter===p.familyId)&&[p.name,p.vendor,p.summary].join(' ').toLowerCase().includes(query.toLowerCase())).length} решений</span></div>
      <div className="ris-market-grid">{registry.products.filter(p=>(filter==='all'||filter===p.familyId)&&[p.name,p.vendor,p.summary].join(' ').toLowerCase().includes(query.toLowerCase())).map(p=><article key={p.id} className={'ris-robot '+(selected===p.id?'selected':'')}><div className="ris-robot-top"><span>{p.familyId.toUpperCase()}</span><span>{p.vendor}</span></div><div className="ris-robot-image"><Box size={53} strokeWidth={1.1}/></div><h3>{p.name}</h3><p>{p.summary}</p><div className="ris-specs">{p.characteristics.slice(0,3).map(c=><div key={c.key}><span>{c.label}</span><strong>{String(c.value)} {c.unit}</strong></div>)}{!p.characteristics.length&&<small>Численные характеристики требуют подтверждения.</small>}</div>
       <div className="ris-source-row">{sourceFor(p).slice(0,2).map(src=><a key={src.id} href={src.url} target="_blank" rel="noreferrer">Источник ↗</a>)}</div>
       <button disabled={p.familyId!=='transport'} className="ris-robot-button" onClick={()=>chooseProduct(p)}>{p.familyId==='transport'?(selected===p.id?'Выбрано для проекта':'Добавить в транспортный сценарий'):'Модуль симуляции недоступен'} <ArrowUpRight size={17}/></button></article>)}</div>
      <div className="ris-next"><span>{chosen?'Выбрано: '+chosen.name:'Выберите мобильного робота для транспортной операции'}</span><button className="ris-primary" onClick={()=>setTab('layout')} disabled={!chosen}>Перейти к планировке <ArrowRight size={19}/></button></div></>}
     {screen==='layout'&&<><div className="ris-page-heading"><span className="ris-mini-label">ЭТАП 03 / ПРОСТРАНСТВО</span><h1>Здесь робот<br/><em>будет работать.</em></h1><p>Перемещайте точки загрузки и разгрузки, проверьте доступность маршрута. CAD, этажность и физическая навигация в этой модели пока недоступны.</p></div>
      <div className="ris-layout-wrap"><div className="ris-layout-pane"><div className="ris-pane-head"><b>{sectorTemplates[scenario.sector].title.toUpperCase()} / ПЛАН 2D</b><span>{scenario.layout.width} × {scenario.layout.height} м</span></div>
      <svg ref={canvasRef} aria-label="Редактор планировки" viewBox={'0 0 '+scenario.layout.width+' '+scenario.layout.height} className="ris-floor" onPointerMove={onMove} onPointerUp={()=>setGrabbed(null)} onPointerCancel={()=>setGrabbed(null)}>
       <defs><pattern id="ris-grid" width="2" height="2" patternUnits="userSpaceOnUse"><path d="M 2 0 L 0 0 0 2" fill="none" stroke="#9eb3c6" strokeWidth=".12"/></pattern></defs><rect width="100%" height="100%" fill="#e9edf0"/><rect width="100%" height="100%" fill="url(#ris-grid)"/>
       {scenario.layout.obstacles.map((o,i)=><rect key={i} x={o.x} y={o.y} width={o.w} height={o.h} rx=".5" fill="#707f88" stroke="#41525b" strokeWidth=".3"/>)}
       {route&&<polyline points={route.points.map(p=>(p.x+.5)+','+(p.y+.5)).join(' ')} fill="none" stroke="#1d62f3" strokeWidth=".7" strokeLinejoin="round" strokeLinecap="round" strokeDasharray="1.6 .7"/>}
       {(['pickup','dropoff'] as const).map((k,i)=><g key={k} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);setGrabbed(k);}} style={{cursor:'grab',touchAction:'none'}}><circle cx={scenario.layout[k].x+.5} cy={scenario.layout[k].y+.5} r="2.2" fill={i?'#ff6b32':'#1260fa'} stroke="#fff" strokeWidth=".5"/><text x={scenario.layout[k].x+.5} y={scenario.layout[k].y+1.15} textAnchor="middle" fontSize="1.6" fill="white" fontWeight="800">{i?'B':'A'}</text></g>)}</svg>
      <div className="ris-map-legend"><span><i className="ris-blue"/> A · загрузка</span><span><i className="ris-orange"/> B · разгрузка</span><span>Серый · препятствие</span></div></div>
      <aside className="ris-layout-data"><span className="ris-mini-label">ПАРАМЕТРЫ МАРШРУТА</span><h3>{route?numeric(route.distance,0)+' м':'Маршрут недоступен'}</h3><p>Расстояние рассчитано поиском кратчайшего пути на сетке 1 м. Динамические препятствия, двери, повороты робота и уклоны не учитываются.</p><div className="ris-detail-line"><span>Точка А</span><b>{scenario.layout.pickup.x}; {scenario.layout.pickup.y}</b></div><div className="ris-detail-line"><span>Точка B</span><b>{scenario.layout.dropoff.x}; {scenario.layout.dropoff.y}</b></div><div className="ris-detail-line"><span>Препятствий</span><b>{scenario.layout.obstacles.length}</b></div>
      <button className="ris-secondary" onClick={()=>change(old=>({...old,layout:structuredClone(sectorTemplates[old.sector].layout)}))}><RotateCcw size={15}/> Восстановить шаблон</button></aside></div><div className="ris-next"><span>{route?'Маршрут построен, можно задать параметры робота.':'Измените расположение точек: маршрут перекрыт.'}</span><button disabled={!route||!chosen} className="ris-primary" onClick={()=>setTab('simulation')}>Настроить симуляцию <ArrowRight size={19}/></button></div></>}

     {screen==='simulation'&&<><div className="ris-page-heading"><span className="ris-mini-label">ЭТАП 04 / SIMULATION STUDIO</span><h1>Сначала<br/><em>модель. Потом ROI.</em></h1><p>Задания, ожидание ресурсов, загрузка парка и зарядка рассчитываются движком SimPy. Анимация планировки не заменяет результат вычислений.</p></div>
      <div className="ris-sim-grid"><div className="ris-work-card"><div className="ris-card-title"><Settings2 size={21}/><h3>Параметры эксперимента</h3></div>
       <div className="ris-fields ris-two-fields">
       <label>Количество роботов <input aria-label="Количество роботов" type="number" min="1" value={scenario.robot.count} onChange={e=>robotField('count',Number(e.target.value))}/></label>
       <label>Рабочая скорость, м/с <input aria-label="Рабочая скорость" type="number" step=".05" min=".05" value={scenario.robot.speedMps} onChange={e=>robotField('speedMps',Number(e.target.value))}/></label>
       <label>Грузоподъёмность, кг <input aria-label="Грузоподъёмность" type="number" value={scenario.robot.payloadKg} onChange={e=>robotField('payloadKg',Number(e.target.value))}/></label>
       <label>Загрузка, секунд <input aria-label="Время загрузки" type="number" value={scenario.robot.loadSeconds} onChange={e=>robotField('loadSeconds',Number(e.target.value))}/></label>
       <label>Разгрузка, секунд <input aria-label="Время разгрузки" type="number" value={scenario.robot.unloadSeconds} onChange={e=>robotField('unloadSeconds',Number(e.target.value))}/></label>
       <label>Батарея, Вт·ч <input aria-label="Ёмкость батареи" type="number" value={scenario.robot.batteryWh} onChange={e=>robotField('batteryWh',Number(e.target.value))}/></label>
       <label>Зарядная мощность, Вт <input aria-label="Зарядная мощность" type="number" value={scenario.robot.chargeW} onChange={e=>robotField('chargeW',Number(e.target.value))}/></label>
       <label>Расход, Вт·ч/м <input aria-label="Расход энергии" type="number" step=".01" value={scenario.robot.whPerMeter} onChange={e=>robotField('whPerMeter',Number(e.target.value))}/></label>
       <label>Количество зарядных постов <input aria-label="Количество зарядных постов" type="number" min="1" value={scenario.robot.chargerCount} onChange={e=>robotField('chargerCount',Number(e.target.value))}/></label>
       <label>Поступление заданий <select aria-label="Поступление заданий" value={scenario.mode} onChange={e=>change(old=>({...old,mode:e.target.value as SimulationInput['mode']}))}><option value="fixed">Равномерно</option><option value="poisson">Случайный поток (Пуассон)</option></select></label>
       <label>Количество прогонов <input aria-label="Количество прогонов" type="number" min="1" max="100" value={replications} onChange={e=>setExperimentReplications(Number(e.target.value))}/></label>
       </div><p className="ris-note">Скорость и расход — эффективные эксплуатационные параметры. Они не выводятся автоматически из паспортной максимальной скорости робота.</p>
       <button className="ris-primary ris-run-button" onClick={execute} disabled={running||!valid||!route||!chosen}>{running?'Вычисление…':'Запустить модель'} <Play size={17}/></button>
       {!chosen&&<p className="ris-error">Сначала выберите роботизированную платформу в маркетплейсе.</p>}{error&&<p role="alert" className="ris-error">{error}</p>}</div>
       <div className="ris-sim-results"><div className="ris-pane-head"><b>ОБЪЕКТ / {scenario.sector.toUpperCase()}</b><span>{experiment?(experiment.replications>1?`SIMPY · ${experiment.replications} прогонов · 95% ДИ`:'SIMPY · 1 прогон'):'ОЖИДАНИЕ ЭКСПЕРИМЕНТА'}</span></div>
        <div className="ris-sim-map"><svg viewBox={'0 0 '+scenario.layout.width+' '+scenario.layout.height} aria-label="Схема маршрута"><rect width="100%" height="100%" fill="#142632"/>{scenario.layout.obstacles.map((o,i)=><rect key={i} x={o.x} y={o.y} width={o.w} height={o.h} fill="#536775" stroke="#81919b" strokeWidth=".2"/>)}{route&&<polyline points={route.points.map(p=>(p.x+.5)+','+(p.y+.5)).join(' ')} fill="none" stroke="#79b4fa" strokeDasharray="1.3 .7" strokeWidth=".7"/>}<circle cx={scenario.layout.pickup.x} cy={scenario.layout.pickup.y} r="1.7" fill="#518cfb"/><circle cx={scenario.layout.dropoff.x} cy={scenario.layout.dropoff.y} r="1.7" fill="#fd7b40"/></svg></div>
        <div className="ris-kpi-grid"><div><small>Среднее выполнено за смену</small><strong>{experiment?interval(experiment.metrics.completed,1):'—'}</strong></div><div><small>Средний остаток заданий</small><strong>{experiment?interval(experiment.metrics.backlog,1):'—'}</strong></div><div><small>Средняя загрузка парка</small><strong>{experiment?interval(experiment.metrics.robotUtilization,1,'%',100):'—'}</strong></div><div><small>Средний расход энергии</small><strong>{experiment?interval(experiment.metrics.energyKwh,1,' кВт·ч'):'—'}</strong></div><div><small>P95 времени задания · серия</small><strong>{experiment?interval(experiment.metrics.p95JobSeconds,1,' с'):'—'}</strong></div><div><small>Средняя загрузка зарядных постов</small><strong>{experiment?interval(experiment.metrics.chargerUtilization,1,'%',100):'—'}</strong></div><div><small>Средний пробег с грузом</small><strong>{experiment?interval(experiment.metrics.loadedMeters,1,' м'):'—'}</strong></div><div><small>Средний холостой пробег</small><strong>{experiment?interval(experiment.metrics.emptyMeters,1,' м'):'—'}</strong></div></div>
        {experiment&&<p className="ris-result-note">Серия из {experiment.replications} прогонов. Выполнено за смену: {interval(experiment.metrics.completed,1)}. Производительность: {interval(experiment.metrics.throughputPerHour,2,'/ч')}. Энергия: {interval(experiment.metrics.energyKwh,2,' кВт·ч')}. Финансовый расчёт использует средние значения серии.</p>}
        <p className="ris-result-note">{result?result.warnings.join(' '):'Показатели появятся после успешного запуска вычислительного сервиса. Декоративная схема не является записью физического движения.'}</p>
        {result&&<button className="ris-primary" onClick={()=>setTab('finance')}>Перейти к инвестициям <ArrowRight size={17}/></button>}</div></div></>}
     {screen==='finance'&&<><div className="ris-page-heading"><span className="ris-mini-label">ЭТАП 05 / INVESTMENT INTELLIGENCE</span><h1>Сколько стоит<br/><em>изменить процесс?</em></h1><p>Финансовые показатели привязаны к результату последнего эксперимента. Данные о стоимости и реализуемой экономии нужно подтвердить отдельно.</p></div>
       {!result&&<div role="alert" className="ris-alert"><Info size={20}/> Сначала выполните имитацию процесса. Без результатов модели ROI и окупаемость не рассчитываются. <button onClick={()=>setTab('simulation')}>К симуляции <ArrowRight size={16}/></button></div>}
       <div className="ris-finance-grid"><div className="ris-work-card"><h3>Исходные данные, ₽</h3><div className="ris-fields ris-two-fields">
       {([['unitPrice','Цена одного робота'],['installation','Монтаж и интеграция'],['infrastructure','Инфраструктура'],['chargersCost','Зарядные станции'],['maintenanceAnnual','Обслуживание / год'],['electricityPerKwh','Электроэнергия, ₽/кВт·ч'],['baselineCostAnnual','Текущие денежные расходы / год'],['residualHumanCostAnnual','Сохраняемые расходы на людей / год'],['daysPerYear','Рабочих смен в год'],['annualDemand','Необходимые операций в год'],['baselineAnnualCompleted','Текущий фактический выпуск / год'],['horizonYears','Горизонт расчёта, лет'],['discountRatePercent','Ставка дисконтирования, %']] as [keyof FinanceInput,string][]).map(([key,label])=><label key={key}>{label}<input type="number" min="0" step={key==='discountRatePercent'?.1:1} aria-label={label} value={finance[key]} onChange={e=>financeField(key,Number(e.target.value))}/></label>)}</div>
       <p className="ris-note">Сокращение времени не считается экономией ФОТ автоматически. Укажите только денежные расходы, которые действительно изменятся после внедрения.</p></div>
       <div className="ris-investment"><span className="ris-mini-label">СЦЕНАРИЙ ПОКУПКИ / {scenario.robot.count} РОБОТОВ</span><div className="ris-finance-top"><span>Капитальные затраты</span><strong>{estimate?currency(estimate.capex):'—'}</strong></div><div className="ris-finance-top"><span>Годовой OPEX комплекса</span><strong>{estimate?currency(estimate.annualOpex):'—'}</strong></div>
        <div className="ris-investment-divider"/><div className="ris-finance-top"><span>ROI за {finance.horizonYears} лет</span><strong className="ris-big-value">{estimate?.roiPercent!==null&&estimate?.roiPercent!==undefined?numeric(estimate.roiPercent)+'%':'Недостаточно данных'}</strong></div>
        <div className="ris-finance-top"><span>Окупаемость</span><strong>{estimate?.paybackYears!==null&&estimate?.paybackYears!==undefined?numeric(estimate.paybackYears,2)+' года':'Не определена'}</strong></div><div className="ris-finance-top"><span>NPV</span><strong>{estimate?.npv!==null&&estimate?.npv!==undefined?currency(estimate.npv):'Не определён'}</strong></div><div className="ris-finance-top"><span>TCO за срок</span><strong>{estimate?currency(estimate.tco):'—'}</strong></div>
        {estimate?.warnings.map(w=><p className="ris-result-note" key={w}>{w}</p>)}
        <p className="ris-note">Годовой объём после внедрения: {estimate?numeric(estimate.annualCompleted,0):'—'} операций. Модель предполагает одинаковую производственную задачу до и после внедрения.</p>
        <button className="ris-primary" onClick={()=>setTab('report')} disabled={!estimate}>Сформировать отчёт <ArrowRight size={19}/></button></div></div></>}

     {screen==='report'&&<><div className="ris-page-heading"><span className="ris-mini-label">ЭТАП 06 / ИТОГИ</span><h1>Проверяемый<br/><em>инвестиционный отчёт.</em></h1><p>Все значения связаны с параметрами конкретного сценария. Показатели, которые невозможно обосновать входными данными, остаются неопределёнными.</p></div>
       {!result?<div className="ris-alert"><Info size={20}/> Нет результата моделирования. Сначала выполните симуляцию. <button onClick={()=>setTab('simulation')}>Перейти к модели <ArrowRight size={16}/></button></div>:
       <div className="ris-report"><div className="ris-report-head"><span>RIS / TECHNICAL & INVESTMENT ASSESSMENT</span><b>{sectorTemplates[scenario.sector].title}</b><p>Операция: {sectorTemplates[scenario.sector].operation} · одна плоскость · источник сценария: пользовательские параметры / демонстрационный шаблон</p></div>
        <div className="ris-report-kpis"><div><small>Количество роботов</small><strong>{scenario.robot.count}</strong></div><div><small>Заявок за смену</small><strong>{experiment?interval(experiment.metrics.created,1):numeric(result.created,0)}</strong></div><div><small>Выполнено за смену</small><strong>{experiment?interval(experiment.metrics.completed,1):numeric(result.completed,0)}</strong></div><div><small>Остаток заявок</small><strong>{experiment?interval(experiment.metrics.backlog,1):numeric(result.backlog,0)}</strong></div></div>
        {experiment&&<><h3>00 / Результаты серии экспериментов</h3><div className="ris-report-row"><span>Количество прогонов</span><b>{experiment.replications}</b></div><div className="ris-report-row"><span>Среднее выполнено за смену</span><b>{interval(experiment.metrics.completed,1)}</b></div><div className="ris-report-row"><span>Средний расход энергии</span><b>{interval(experiment.metrics.energyKwh,2,' кВт·ч')}</b></div><p className="ris-note">95% ДИ характеризует статистическую неопределённость оценки среднего в рамках этой модели; он не является гарантией выполнения плана на реальном предприятии. Приведённые ниже детальные показатели относятся только к первому прогону; экономика рассчитана по средним серии с дополнительной проверкой разброса производительности.</p></>}
        <h3>01 / Технический результат · первый прогон</h3><div className="ris-report-row"><span>Движок и версия</span><b>{result.engine} · {result.engineVersion}</b></div><div className="ris-report-row"><span>Длина маршрута</span><b>{numeric(result.routeMeters)} м</b></div><div className="ris-report-row"><span>Среднее ожидание до обслуживания (включая зарядку)</span><b>{numeric(result.meanQueueMinutes)} мин</b></div><div className="ris-report-row"><span>Коэффициент использования роботов</span><b>{numeric(result.robotUtilization*100)}%</b></div><div className="ris-report-row"><span>Энергия на смену</span><b>{numeric(result.energyKwh)} кВт·ч</b></div>
        <div className="ris-report-row"><span>Среднее время задания</span><b>{result.meanJobSeconds!=null?numeric(result.meanJobSeconds)+' с':'Недостаточно выполненных заданий'}</b></div><div className="ris-report-row"><span>P95 времени задания</span><b>{result.p95JobSeconds!=null?numeric(result.p95JobSeconds)+' с':'Недостаточно выполненных заданий'}</b></div><div className="ris-report-row"><span>Пробег с грузом</span><b>{numeric(result.loadedMeters)} м</b></div><div className="ris-report-row"><span>Холостой пробег</span><b>{numeric(result.emptyMeters)} м</b></div><div className="ris-report-row"><span>Загрузка зарядных постов</span><b>{numeric(result.chargerUtilization*100)}%</b></div>
        <h3>02 / Экономика</h3><div className="ris-report-row"><span>CAPEX</span><b>{estimate?currency(estimate.capex):'Не рассчитан'}</b></div><div className="ris-report-row"><span>OPEX комплекса за год</span><b>{estimate?currency(estimate.annualOpex):'Не рассчитан'}</b></div><div className="ris-report-row"><span>ROI</span><b>{estimate?.roiPercent!==null&&estimate?.roiPercent!==undefined?numeric(estimate.roiPercent)+'%':'Недостаточно данных'}</b></div><div className="ris-report-row"><span>NPV</span><b>{estimate?.npv!==null&&estimate?.npv!==undefined?currency(estimate.npv):'Недостаточно данных'}</b></div>
        <h3>03 / Ограничения</h3>{[...result.warnings,...(estimate?.warnings??[])].map(w=><p key={w} className="ris-report-warning"><ShieldAlert size={17}/>{w}</p>)}
        <div className="ris-report-actions"><button className="ris-primary" onClick={()=>download('ris-investment-assessment.json',{model:scenario,robot:chosen?{id:chosen.id,name:chosen.name,sourceIds:chosen.sourceIds}:null,simulation:result,experiment,financeInputs:finance,investment:estimate,limitations:[...result.warnings,...(estimate?.warnings??[])]})}><Download size={17}/> Скачать JSON отчёта</button><button className="ris-secondary" onClick={()=>window.print()}>Печать отчёта</button></div></div>}</>}
    </main></div>}
  <footer className="ris-global-footer"><b>RIS / ROBOT INVESTMENT STUDIO</b><span>Независимый инструмент предварительной оценки роботизации · 2026</span><button onClick={()=>setTab('welcome')}>На главную ↑</button></footer>
 </div>;
}
