/** Local-only auth infrastructure checks. No fabricated business or economic fixture. */
import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {randomBytes,randomUUID} from 'node:crypto';
import {createClient} from '@supabase/supabase-js';
import app from '../apps/api/app';
const output=execFileSync(process.execPath,['node_modules/supabase/dist/supabase.js','status','--output','json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']});
const settings=JSON.parse(output.slice(output.indexOf('{')));
const url:string=settings.API_URL;const key:string=settings.ANON_KEY;const service:string=settings.SERVICE_ROLE_KEY;
if(!url||!key||!service||!/^http:\/\/(127\.0\.0\.1|localhost):\d+$/.test(url))throw new Error('Only a running local Supabase is permitted for this verification.');
const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const identities:Array<{id:string;email:string;token:string}>=[];const checks:string[]=[];
const ensure=(condition:unknown,label:string)=>{if(!condition)throw new Error(label);checks.push(label);};
const bindings={SUPABASE_URL:url,SUPABASE_ANON_KEY:key};let validationOrg:string|null=null;
async function request(path:string,token:string,method='GET',body?:unknown){const response=await app.request('http://127.0.0.1:8787/api/v1'+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})},bindings);return {status:response.status,data:await response.json()};}
try{
 for(const role of ['owner','viewer','outsider']){const email=`access-check-${role}-${randomUUID()}@example.invalid`;const password=randomBytes(32).toString('base64url');const {data,error}=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{purpose:'temporary authorization verification'}});if(error||!data.user)throw error??new Error('Identity creation failed');identities.push({id:data.user.id,email,token:''});const client=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const login=await client.auth.signInWithPassword({email,password});if(login.error||!login.data.session)throw login.error??new Error('Local identity login failed');identities[identities.length-1].token=login.data.session.access_token;}
 const [owner,viewer,outsider]=identities;
 const created=await request('/organizations',owner.token,'POST',{name:'Проверка изоляции доступа'});ensure(created.status===201,'Owner creates an isolated validation organization');const org=created.data.organization.id;validationOrg=org;
 const saved=await request('/organizations/'+org+'/scenarios',owner.token,'POST',{name:'Пустое состояние проверки доступа',payload:{}});ensure(saved.status===201,'Owner saves an empty payload');const id=saved.data.scenario.id;
 const invited=await request('/organizations/'+org+'/invitations',owner.token,'POST',{email:viewer.email,role:'viewer'});ensure(invited.status===201,'Owner creates viewer invitation');const invite=invited.data.invitation.token;
 ensure((await request('/invitations/accept',outsider.token,'POST',{token:invite})).status===403,'Wrong recipient cannot accept invitation');
 ensure((await request('/invitations/accept',viewer.token,'POST',{token:invite})).status===200,'Intended verified recipient accepts invitation');
 ensure((await request('/invitations/accept',viewer.token,'POST',{token:invite})).status===403,'Invitation cannot be replayed');
 ensure((await request('/organizations/'+org+'/scenarios',viewer.token)).data.scenarios.length===1,'Viewer can read its organization');
 ensure((await request('/organizations/'+org+'/scenarios',viewer.token,'POST',{name:'Forbidden empty state',payload:{}})).status===403,'Viewer cannot write through API');
 ensure((await request('/organizations/'+org+'/scenarios',outsider.token)).data.scenarios.length===0,'Outsider cannot read tenant scenarios');
 ensure((await request('/organizations/'+org+'/scenarios',outsider.token,'POST',{name:'Forbidden empty state',payload:{}})).status===403,'Outsider cannot write tenant scenarios');
 const updated=await request('/organizations/'+org+'/scenarios/'+id,owner.token,'PUT',{name:'Пустое состояние: новая версия',payload:{},expectedVersion:1});ensure(updated.status===200,'Version update succeeds');
 ensure((await request('/organizations/'+org+'/scenarios/'+id,owner.token,'PUT',{name:'Stale empty state',payload:{},expectedVersion:1})).status===409,'Stale version is rejected');
 ensure((await request('/organizations/'+org+'/scenarios/'+id+'/history',owner.token)).data.history.length===2,'History is atomically preserved');
 ensure(JSON.stringify((await request('/organizations/'+org+'/scenarios/'+id+'/export',owner.token)).data.scenario.payload)==='{}','Export retains exact empty payload');
 const sql=readFileSync('tests/rls-isolation.sql','utf8');execFileSync('docker',['exec','-i','supabase_db_robotization-platform','psql','-U','postgres','-d','postgres','-v','ON_ERROR_STOP=1','-v','owner_id='+owner.id,'-v','viewer_id='+viewer.id,'-v','outsider_id='+outsider.id],{input:sql,stdio:['pipe','pipe','pipe']});checks.push('PostgreSQL RLS checks passed directly, beyond Hono');
 if(process.argv.includes('--restore')){const container='supabase_db_robotization-platform';const restored='restore_check_'+randomUUID().replaceAll('-','');const dump='/tmp/'+restored+'.dump';let created=false;try{execFileSync('docker',['exec',container,'pg_dump','-U','postgres','-d','postgres','--format=custom','--no-owner','--schema=public','--schema=auth','--file='+dump],{stdio:'pipe'});execFileSync('docker',['exec',container,'createdb','-U','postgres',restored],{stdio:'pipe'});created=true;execFileSync('docker',['exec',container,'psql','-U','postgres','-d',restored,'-v','ON_ERROR_STOP=1','-c','DROP SCHEMA public; CREATE SCHEMA IF NOT EXISTS extensions; CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;'],{stdio:'pipe'});execFileSync('docker',['exec',container,'pg_restore','-U','supabase_admin','-d',restored,'--exit-on-error','--no-owner',dump],{stdio:'pipe'});execFileSync('docker',['exec','-i',container,'psql','-U','postgres','-d',restored,'-v','ON_ERROR_STOP=1','-v','owner_id='+owner.id,'-v','viewer_id='+viewer.id,'-v','outsider_id='+outsider.id],{input:sql,stdio:['pipe','pipe','pipe']});checks.push('Logical backup restored into a separate database and RLS/history checks passed again');}finally{if(created)execFileSync('docker',['exec',container,'dropdb','-U','postgres',restored],{stdio:'pipe'});execFileSync('docker',['exec',container,'rm','-f',dump],{stdio:'pipe'});}}
 mkdirSync('output',{recursive:true});writeFileSync('output/database-verification.json',JSON.stringify({status:'passed',checkedAt:new Date().toISOString(),checks,limitations:['Local identity tests only; Google OAuth and cloud deployment not exercised.','Business payloads are empty; no economic scenario fabricated.']},null,2));
 console.log(JSON.stringify({status:'passed',checks:checks.length,report:'output/database-verification.json'}));
}finally{const cleanupErrors:unknown[]=[];if(validationOrg){const {error}=await admin.from('organizations').delete().eq('id',validationOrg);if(error)cleanupErrors.push(error);}for(const user of identities){const {error}=await admin.auth.admin.deleteUser(user.id);if(error)cleanupErrors.push(error);}if(cleanupErrors.length){console.error('Temporary identity cleanup failed; inspect local database.');process.exitCode=1;}}
